services:
  db:
    image: postgres:15
    container_name: postgres-carros
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=carrosdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
